
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ASUS ROG
 */
public class AplikasiKontak extends javax.swing.JFrame {

    /**
     * Creates new form AplikasiKontak
     */
    public AplikasiKontak() {
        initComponents();
        tampil();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        noTextField = new javax.swing.JTextField();
        namaTextField = new javax.swing.JTextField();
        TambahButton = new javax.swing.JButton();
        EditButton = new javax.swing.JButton();
        HapusButton = new javax.swing.JButton();
        CariButton = new javax.swing.JButton();
        ImportButton = new javax.swing.JButton();
        EksportButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        KontakTable = new javax.swing.JTable();
        cariTextField = new javax.swing.JTextField();
        keluarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setText("aplikasi pegelola kontak");
        jPanel2.add(jLabel1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jLabel2.setText("Maukkan Nama :");

        jLabel3.setText("Nomor Telepon :");

        jLabel4.setText("Kategori :");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kategori", "Keluarga", "Teman", "Kerja" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        TambahButton.setText("Tambah");
        TambahButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahButtonActionPerformed(evt);
            }
        });

        EditButton.setText("Edit");
        EditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonActionPerformed(evt);
            }
        });

        HapusButton.setText("Hapus");
        HapusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusButtonActionPerformed(evt);
            }
        });

        CariButton.setText("Cari");
        CariButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CariButtonActionPerformed(evt);
            }
        });

        ImportButton.setText("Import");

        EksportButton.setText("Eksport");
        EksportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EksportButtonActionPerformed(evt);
            }
        });

        KontakTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(KontakTable);

        keluarButton.setText("Keluar");
        keluarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(CariButton)
                        .addGap(27, 27, 27)
                        .addComponent(cariTextField))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(105, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(TambahButton)
                                .addGap(6, 6, 6)
                                .addComponent(EditButton)
                                .addComponent(HapusButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(keluarButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(namaTextField)
                                    .addComponent(noTextField)
                                    .addComponent(jComboBox1, 0, 203, Short.MAX_VALUE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(ImportButton)
                        .addGap(29, 29, 29)
                        .addComponent(EksportButton)))
                .addGap(69, 69, 69))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ImportButton)
                    .addComponent(EksportButton))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(noTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TambahButton)
                    .addComponent(EditButton)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(HapusButton)
                        .addComponent(keluarButton)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CariButton)
                    .addComponent(cariTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
        
        
    private void TambahButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahButtonActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "insert into data_kontak (nama, nomor_telpon,kategori) values('"
                    +namaTextField.getText()+"','"
                    +noTextField.getText()+"','"
                    +jComboBox1.getSelectedItem()+"')";
                 java.sql.Connection conn=(java.sql.Connection) koneksi.koneksiDB();
                 java.sql.PreparedStatement pst= conn.prepareStatement(sql);
                 pst.execute();
                 JOptionPane.showMessageDialog(null, "Data Berhasil disimpan");
                 tampil();
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, "Data Gagal disimpan");
            System.out.println(e.getMessage());

        }
    }//GEN-LAST:event_TambahButtonActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void EditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonActionPerformed
        // TODO add your handling code here:
        try {
            java.sql.Connection conn = (java.sql.Connection) koneksi.koneksiDB();
            String sql = "UPDATE data_kontak SET nomor_telpon=?,  Kategori=? WHERE nama=?";
             if (namaTextField.getText().isEmpty() || noTextField.getText().isEmpty() ) {
                JOptionPane.showMessageDialog(null, "Harap lengkapi semua data!");
                return;
            }
            
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            
            pst.setString(1, noTextField.getText());
            pst.setString(2, jComboBox1.getSelectedItem().toString()); // Kategori
            pst.setString(3, namaTextField.getText());
            
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil Diperbarui");
            tampil();
 
            //mengatur nilai
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data gagal diperbarui"+e.getMessage());
        }
    }//GEN-LAST:event_EditButtonActionPerformed

    private void HapusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusButtonActionPerformed
        // TODO add your handling code here:
         try {
            java.sql.Connection conn = (java.sql.Connection) koneksi.koneksiDB();
            String sql = "delete from data_kontak where "+namaTextField.getText()+"'";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Data berhasil di hapus");
            tampil();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data tidak berhasil di hapus");
            System.out.println("e.getMessage()");
        }
    }//GEN-LAST:event_HapusButtonActionPerformed

    private void keluarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_keluarButtonActionPerformed

    private void CariButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CariButtonActionPerformed
        // TODO add your handling code here:
         try {
            java.sql.Connection conn=(java.sql.Connection)koneksi.koneksiDB();
            String sql = "select * from data_kontak where nama= '"+cariTextField.getText()+"' or nomor_telpon= '"+cariTextField.getText()+"'";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery(sql);
            if (rs.next()) {
                namaTextField.setText(rs.getNString(2));
                noTextField.setText(rs.getNString(3));
                jComboBox1.setSelectedItem(rs.getString(4));
                JOptionPane.showMessageDialog(null, "Data Kontak " +cariTextField.getText()+" Ditemukan");
                tampil();
            }
        } catch (Exception e) {
            cariTextField.requestFocus();
        }
    }//GEN-LAST:event_CariButtonActionPerformed

    private void EksportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EksportButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
         int returnValue = file.showSaveDialog(this);
         
         if (returnValue == JFileChooser.APPROVE_OPTION) {
             String filePath = file.getSelectedFile().getAbsolutePath();
             
             try (BufferedWriter writer = new BufferedWriter(new FileWriter(filePath))) {
                 writer.write("id,nama,nomor_Telepon,kategori\n"); // Header CSV
                java.sql.Connection conn = (java.sql.Connection) koneksi.koneksiDB();
                String sql = "SELECT * FROM data_kontak";
                java.sql.PreparedStatement pst= conn.prepareStatement(sql);
                ResultSet rs = pst.executeQuery(sql);
                writer.write("nama\t,nomor_telepon\t,kategori\n");
                while (rs.next()) {
                    writer.write(
                            rs.getString(2) + "\t" +
                            rs.getString(3) + "\t" +
                            rs.getString(4) + "\n" 
                    );
                }
                
                 
             } catch (Exception e) {
                 JOptionPane.showMessageDialog(null, "data"+filePath+"sukses");
             }
            
        }
    }//GEN-LAST:event_EksportButtonActionPerformed


   
        private void tambah(String nama,String nomor,String kategori){
        
        String sql = "INSERT INTO data_kontak (nama,telepon,kategori) VALUES (?,?,?)";
        
            try (Connection conn = koneksi.koneksiDB();
                    PreparedStatement input = conn.prepareStatement(sql)) {
                    
                    input.setString(1, nama);
                    input.setString(2, nomor);
                    input.setString(3, kategori);
                    input.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Kontak Berhasil ditambahkan");
            } catch (Exception e) {
            }
        }
        
        private void tampil(){
            try {
            DefaultTableModel tabel = new DefaultTableModel();
        tabel.addColumn("Nama");
        tabel.addColumn("Nomor Telepon");
        tabel.addColumn("Kategori");
            java.sql.Connection conn = (java.sql.Connection) koneksi.koneksiDB();
            String sql = "SELECT * FROM data_kontak";
            java.sql.PreparedStatement pst= conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery(sql);
                while (rs.next()){
                    tabel.addRow(new Object[]{
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4)
                    });
                    KontakTable.setModel(tabel);
                }
        } catch (Exception e) {
            System.out.println("error : "+ e.getMessage());
        }
        }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiKontak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiKontak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiKontak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiKontak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiKontak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CariButton;
    private javax.swing.JButton EditButton;
    private javax.swing.JButton EksportButton;
    private javax.swing.JButton HapusButton;
    private javax.swing.JButton ImportButton;
    private javax.swing.JTable KontakTable;
    private javax.swing.JButton TambahButton;
    private javax.swing.JTextField cariTextField;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton keluarButton;
    private javax.swing.JTextField namaTextField;
    private javax.swing.JTextField noTextField;
    // End of variables declaration//GEN-END:variables
}
